In [9]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "junaid512/credit-scoring-dataset-creditworthiness-prediction",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_10164/3675837280.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:    Age  Gender    Education  Income   Debt  Credit_Score  Loan_Amount  \
0   56  Female       Master  149406  34089           581        49200
1   69  Female  High School   78896   8626           648        20147
2   46  Female       Master  119339  46281           329        41307
3   32    Male  High School  131067  29403           816        19019
4   60    Male          PhD   38001  30032           673        16317

   Loan_Term  Num_Credit_Cards Payment_History Employment_Status  \
0         60                 4             Bad        Unemployed
1         24                 7            Good          Employed
2         12                 8             Bad        Unemployed
3         60                 8             Bad          Employed
4         36                 4         Average          Employed

  Residence_Type Marital_Status  Creditworthiness
0         Rented         Single                 1
1      Mortgaged        Married                 1
2          Owned         Single                 1
3          Owned         Single                 1
4         Rented        Married                 0

In [10]:
df

,Age,Gender,Education,Income,Debt,Credit_Score,Loan_Amount,Loan_Term,Num_Credit_Cards,Payment_History,Employment_Status,Residence_Type,Marital_Status,Creditworthiness
0,56,Female,Master,149406,34089,581,49200,60,4,Bad,Unemployed,Rented,Single,1
1,69,Female,High School,78896,8626,648,20147,24,7,Good,Employed,Mortgaged,Married,1
2,46,Female,Master,119339,46281,329,41307,12,8,Bad,Unemployed,Owned,Single,1
3,32,Male,High School,131067,29403,816,19019,60,8,Bad,Employed,Owned,Single,1
4,60,Male,PhD,38001,30032,673,16317,36,4,Average,Employed,Rented,Married,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,69,Male,Bachelor,124894,46777,364,43499,12,4,Bad,Self-Employed,Owned,Single,0
11996,20,Male,High School,137088,49119,758,44320,24,7,Average,Unemployed,Rented,Single,1
11997,66,Male,High School,26768,2823,523,37458,48,6,Bad,Employed,Owned,Married,1
11998,61,Female,PhD,79214,36508,775,31916,24,7,Average,Employed,Mortgaged,Divorced,1
11999,49,Male,High School,38972,35556,625,42760,48,7,Bad,Unemployed,Rented,Divorced,0

In [15]:
import pandas as pd

X = pd.get_dummies(df.drop(columns='Creditworthiness'), dtype=int)
y = df['Creditworthiness'].to_numpy(dtype=int)

print(X.dtypes.unique())
print(X.shape)

[dtype('int64')]
(12000, 25)

In [16]:
X

,Age,Income,Debt,Credit_Score,Loan_Amount,Loan_Term,Num_Credit_Cards,Gender_Female,Gender_Male,Education_Bachelor,...,Payment_History_Good,Employment_Status_Employed,Employment_Status_Self-Employed,Employment_Status_Unemployed,Residence_Type_Mortgaged,Residence_Type_Owned,Residence_Type_Rented,Marital_Status_Divorced,Marital_Status_Married,Marital_Status_Single
0,56,149406,34089,581,49200,60,4,1,0,0,...,0,0,0,1,0,0,1,0,0,1
1,69,78896,8626,648,20147,24,7,1,0,0,...,1,1,0,0,1,0,0,0,1,0
2,46,119339,46281,329,41307,12,8,1,0,0,...,0,0,0,1,0,1,0,0,0,1
3,32,131067,29403,816,19019,60,8,0,1,0,...,0,1,0,0,0,1,0,0,0,1
4,60,38001,30032,673,16317,36,4,0,1,0,...,0,1,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,69,124894,46777,364,43499,12,4,0,1,1,...,0,0,1,0,0,1,0,0,0,1
11996,20,137088,49119,758,44320,24,7,0,1,0,...,0,0,0,1,0,0,1,0,0,1
11997,66,26768,2823,523,37458,48,6,0,1,0,...,0,1,0,0,0,1,0,0,1,0
11998,61,79214,36508,775,31916,24,7,1,0,0,...,0,1,0,0,1,0,0,1,0,0
11999,49,38972,35556,625,42760,48,7,0,1,0,...,0,0,0,1,0,0,1,1,0,0

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
import numpy as np

class Perceptron:
    def __init__(self, learning_rate=0.01, epochs=100):
        self.lr = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None

    def _step_function(self, x):
        return np.where(x >= 0, 1, 0)

    def fit(self, X, y):
        num_samples, num_features = X.shape

        self.weights = np.random.uniform(-0.5, 0.5, num_features)
        self.bias = np.random.uniform(-0.5, 0.5)

        for epoch in range(self.epochs):
            linear_output = np.dot(X, self.weights) + self.bias
            y_predicted = self._step_function(linear_output)
            update = self.lr * (y - y_predicted)

            self.weights += np.dot(X.T, update)  
            self.bias += np.sum(update)

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        return self._step_function(linear_output)

In [ ]:
P = Perceptron(learning_rate=0.1, epochs=10)
P.fit(X_train, y_train)
model = P

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, model.predict(X_test))

AttributeError: 'NoneType' object has no attribute 'predict'